### ISSUE TITLE
Compatability with better combat

### ISSUE THREAD

**Issue by Los2tale** [CCr4ft3r/actions-of-stamina#1] opened 2023-04-03 01:08 UTC
I can continue attacking without stamina when install better combat

**Comment by Aceplante2** [comment] 2023-04-10 07:20
I dont have this issue?

**Comment by BookerCatch** [comment] 2023-04-26 23:51
After some testing, the stamina consumption per attack is nullified if "Hold to Attack" is enabled in Better Combat's config. The feathers are consumed, but the player can still attack indefinitely. If Hold to Attack is disabled, both mods work as expected.

**Comment by CCr4ft3r** [comment] 2023-05-03 17:56
Thx for reporting and pointing out the cause. I fixed it and it will be included in the next feature update

**Closed by CCr4ft3r** 2023-05-03 17:56 UTC
